### ISSUE TITLE
Failed to copy AMI 2.3

### ISSUE THREAD

**Issue by ambantis** [scylladb/scylla-ami#42]
This seems related to #38; attempted to copy `ami-0da599147b1d9e80d` from us-west-2 to us-east-2 (ohio), which fails with

```
You do not have permission to access the storage of this ami
```

**Comment by devwout** [comment]
Same for the latest AMI `ami-03415e87997ef789b`. Perhaps the release process should include making the EBS snapshot of the AMI public.

Copying an AMI is required to have an encrypted EBS root device. Public EBS snapshots can also be copied between regions, so in a way it resolves #48 because people could copy the image to their region.

**Comment by tzach** [comment]
@syuu1228 I remember this issue was solved for later Scylla version. Is this the case?

**Comment by tzach** [comment]
@devwout can you please test with a latest Scylla AMI (3.0) ?

**Comment by devwout** [comment]
I tried copying ami-08e617d9f57f477ee (latest version on the website) to the same region (US East 1) but I still get an error message "The storage for the ami is not available in the source region."

**Comment by devwout** [comment]
This still does not work for ScyllaDB 3.1.1 ami-0997b8d749daad633. I see a new issue has been filed #52 .

Is a fix for this incoming? We are waiting for this to update our cluster because we require an encrypted root file system on AWS.

**Comment by devwout** [comment]
Any news on this?

**Comment by devwout** [comment]
It is still not possible to copy the most recent AMIs. Is there any way the permission change could be integrated into the image build process, so users caring about security can have an encrypted root device?

**Comment by tzach** [comment]
@syuu1228 ?
